### ISSUE TITLE
Mega.nz link is down

### ISSUE THREAD

**Issue by WildSpy-tech** [cryptoAlgorithm/nt5src#1]
Mega.nz link is down

**Comment by modineandrew** [comment]
It's been down for a while now. There might be a new link somewhere, however.

**Comment by 1alessandro1** [comment]
[Microsoft leaked source code archive_2020-10-04.torrent.zip](https://github.com/cryptoAlgorithm/nt5src/files/5929043/Microsoft.leaked.source.code.archive_2020-10-04.torrent.zip)

**Comment by cryptoAlgorithm** [comment]
Duplicate of #2
